// © 2015 George King. Permission to use this file is granted in license-quilt.txt.
// This file is generated by gen/vec.py.

import Darwin
import simd
import QuiltArithmetic


extension SIMD2: Vec, Vec2 where Scalar: ArithmeticProtocol { // Float/Int agnostic.
  public typealias VFType = V2F
  public typealias VDType = V2D
  public typealias VU8Type = V2U8
  public typealias V2Type = SIMD2

  public init(_ v: V2F) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2D) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2I) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2I8) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2I16) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2I32) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2U8) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2U16) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V2U32) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3F) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3D) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3I) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3I8) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3I16) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3I32) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3U8) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3U16) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V3U32) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4F) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4D) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4I) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4I8) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4I16) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4I32) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4U8) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4U16) {
    self.init(Scalar(v.x), Scalar(v.y))
  }
  public init(_ v: V4U32) {
    self.init(Scalar(v.x), Scalar(v.y))
  }

  public static var scalarCount: Int { 2 }
  public static var zero: Self { Self.init() }
  public static var one: Self { Self.init(1, 1) }

  public func dot(_ b: SIMD2<Scalar>) -> F64 {
    var s = x.asF64 * b.x.asF64
    s += y.asF64 * b.y.asF64
    return s
  }

}


extension SIMD2: FloatVec, FloatVec2 where Scalar: ArithmeticFloat { // Float-specific.

  public var allFinite: Bool { x.isFinite && (y.isFinite) }
  public var allZero: Bool { x.isZero && (y.isZero) }
  public var allZeroOrSubnormal: Bool { x.isZeroOrSubnormal && (y.isZeroOrSubnormal) }
  public var anySubnormal: Bool { x.isSubnormal || (y.isSubnormal)}
  public var anyInfite: Bool { x.isInfinite || (y.isInfinite)}
  public var anyNaN: Bool { x.isNaN || (y.isNaN)}
  public var anyZero: Bool { x.isZero && (y.isZero) }
  public var anyZeroOrSubnormal: Bool { x.isZeroOrSubnormal || (y.isZeroOrSubnormal) }
  public var clampToUnit: SIMD2 { SIMD2(x.clamp(min: 0, max: 1), y.clamp(min: 0, max: 1)) }
  public var clampToSignedUnit: SIMD2 { SIMD2(x.clamp(min: -1, max: 1), y.clamp(min: -1, max: 1)) }
  public var toU8Pixel: VU8Type { VU8Type(U8((x*255).clamp(min: 0, max: 255)), U8((y*255).clamp(min: 0, max: 255))) }
}


extension SIMD2: Comparable where Scalar: Comparable{
  public static func <(a: SIMD2, b: SIMD2) -> Bool {
    if a.x != b.x { return a.x < b.x }
    return a.y < b.y
  }
}

